Fixed (and added) tests for trimmer set (#10)
* Fixed gzip's test

* Fixed netstat tests

* Fixed thttpd test

* thttpd fix

* Fixed wget test

* Fixed aircrack test

* Made sans build.sh more general

* Fixed dnsproxy test

* Fixed totd test

* Fixed objdump test

* gprof tests fixed

* Fixed bzip2 test

* Added airtun test

* Added yices test

* Cleaned up airtun scripts

* Removed gprof and objdump bc files

* Added test.sh script for airtun

* Added netperf test

* Cleaned up bzip2 files

* Added memcached tests

* Fixed mini_httpd test

* Renaming test

* Added curl test and install dependency script

* Removed hanging comma from the end of set

* Added server found check in sans

* Removed unnecessary sudo, fixed some tests

diff --git a/examples/trimmer/thttpd/Makefile b/examples/trimmer/thttpd/Makefile
--- a/examples/trimmer/thttpd/Makefile
+++ b/examples/trimmer/thttpd/Makefile
@@ -4,14 +4,14 @@ THTTPD_VERSION=2.25b
 THTTPD_NAME=${THTTPD}-${THTTPD_VERSION}
 THTTPD_TAR=${THTTPD_NAME}.tar.gz
 THTTPD_PATCH=thttpd.patch
-
+THTTPD_CONF=thttpd.conf
 THTTPD_MANIFEST=${THTTPD}.manifest
 
 HELPER_SCRIPT=./build.sh
 HELPER_TAR=helper_scripts_and_files.tar.gz
 
 
-OUT_DIR?=trimmer
+OUT_DIR?=slash
 LOG_FILE?=logs
 
 BITCODE_WRAPPER?=gclang
@@ -19,12 +19,34 @@ BITCODE_EXTRACT?=get-bc
 
 all: ${THTTPD_BITCODE}
 
-compress: ${OUT_DIR}
-	cp ${THTTPD_BITCODE} ${OUT_DIR} && \
-	cp ${THTTPD}.conf ${OUT_DIR} && \
-	cd ${OUT_DIR} && \
-	echo '{"binary": "thttpd_fin", "native_libs": [], "name": "thttpd", "args": ["-C",  "thttpd.conf"], "modules": [], "ldflags": ["-lcrypt"], "main": "thttpd.bc", "config_files": ["thttpd.conf"]}' > ${THTTPD_MANIFEST} && \
-	python ${TRIMMER_HOME}/tool/trimmer.py ${THTTPD_MANIFEST} ./ 2> ${LOG_FILE}
+test:
+	@echo "\t\tTesting Thttpd"
+	@cd ${OUT_DIR}/ && \
+        mkdir -p workdir && \
+        echo '<HTML><HEAD><TITLE>Index of ./</TITLE></HEAD><BODY BGCOLOR="#99cc99" TEXT="#000000" LINK="#2020ff" VLINK="#4040cc"><H4>Index of ./</H4></HTML>' > workdir/index.html && \
+        ./thttpd_fin_stripped && \
+        cd ../ && \
+        sleep 1
+	wget 127.0.0.1:8087/
+	@rm -r slash/workdir
+	cp ${THTTPD_CONF} ${THTTPD_NAME}
+	sed -i 's/8087/8199/g' ${THTTPD_NAME}/${THTTPD_CONF}
+	@mkdir -p ${THTTPD_NAME}/workdir
+	@echo '<HTML><HEAD><TITLE>Index of ./</TITLE></HEAD><BODY BGCOLOR="#99cc99" TEXT="#000000" LINK="#2020ff" VLINK="#4040cc"><H4>Index of ./</H4></HTML>' > ${THTTPD_NAME}/workdir/index.html && \
+        cd ${THTTPD_NAME} && \
+        ./thttpd -C ${THTTPD_CONF}
+	sleep 1
+	cd ${THTTPD_NAME} && \
+        wget 127.0.0.1:8199/
+	@cmp -s ${THTTPD_NAME}/index.html.1 index.html; \
+        RETVAL=$$?; \
+        if [ $$RETVAL -eq 0 ]; then \
+                echo "\tthttpd test baseline compare? Passed!"; \
+        else \
+                echo "\tthttpd test baseline compare? Failed!"; \
+        fi
+	@rm -r ${THTTPD_NAME}/workdir
+	@rm ${THTTPD_NAME}/index.html.1 index.html
 
 .PHONY: ${THTTPD_BITCODE}
 ${THTTPD_BITCODE}: ${THTTPD_NAME} 
diff --git a/examples/trimmer/yices/Makefile b/examples/trimmer/yices/Makefile
--- a/examples/trimmer/yices/Makefile
+++ b/examples/trimmer/yices/Makefile
@@ -15,24 +15,44 @@ BITCODE_EXTRACT?=get-bc
 
 all: ${YICES_BITCODE}
 
+test:
+	@echo "\t\tTest Yices"
+	./yices_occamized_stripped > t_out && \
+	${YICES_NAME}/build/x86_64-pc-linux-gnu-release/bin/yices_main --logic=QF_AUFBV ./yices-2.6.1/examples/bool_eqs.ys > o_out
+	@echo "Output comparison to Baseline:"
+	@cmp -s ./t_out o_out; \
+	RETVAL=$$?; \
+	if [ $$RETVAL -eq 0 ]; then \
+		echo "\tyices test baseline compare? Passed!"; \
+	else \
+		echo "\tyices test baseline compare? Failed!"; \
+	fi
+	@rm ./o_out
+	@rm ./t_out
+
 ${YICES_BITCODE}: ${YICES_NAME}
 	cd ${YICES_NAME} && \
 	./configure CC=gclang && \
 	sed -i 's/gcc/gclang -fno-inline -fno-inline-functions -Xclang -disable-O0-optnone -O2/g' src/Makefile && \
 	CC=${BITCODE_WRAPPER} make && \
-	${BITCODE_EXTRACT} ./${YICES_NAME}/build/x86_64-pc-linux-gnu-release/bin/${YICES}_main && \
-	mv ./${YICES_NAME}/build/x86_64-pc-linux-gnu-release/bin/${YICES_BITCODE} ../
-	cp ./${YICES_NAME}/build/x86_64-pc-linux-gnu-release/lib/libyices.a ../
+  ${BITCODE_EXTRACT} build/x86_64-pc-linux-gnu-release/bin/${YICES}_main && \
+	mv build/x86_64-pc-linux-gnu-release/bin/${YICES_BITCODE} ../ && \
+	cp build/x86_64-pc-linux-gnu-release/lib/libyices.a ../
 
 ${YICES_NAME}:
-	wget https://yices.csl.sri.com/releases/${YICES_VERSION}/${YICES_TAR}
-	tar -xvzf ./${YICES_TAR}
+	wget https://github.com/SRI-CSL/yices2/archive/refs/tags/Yices-2.6.1.tar.gz && \
+	mv Yices-2.6.1.tar.gz ${YICES_TAR} && \
+	tar -xvzf ${YICES_TAR} && \
+	mv yices2-Yices-2.6.1 ${YICES_NAME} && \
+	cd ${YICES_NAME} && autoconf && \
+	cd ..
 
 clean:
-	rm *.bc
-	rm yices.manifest
-	rm -f yices_occamized yices_occamized_stripped
-	rm -f ${YICES_TAR}
+	-rm *.bc *.a
+	-rm yices.manifest
+	-rm -f yices_occamized yices_occamized_stripped yices_main_orig
+	-rm -rf slash
+	-rm -f ${YICES_TAR}
 
 realclean: clean
-	rm -rf ${YICES_NAME}
+	-rm -rf ${YICES_NAME}
